workflows:
  android-apk:
    name: jayemath_water_v185_newayematJh Water Project V185 APK
    max_build_duration: 120

    environment:
      android_signing:
       - jayemath_water_v185_new

    scripts:
      - name: Set Android SDK location
        script: |
          echo "sdk.dir=$ANDROID_SDK_ROOT" > "$CM_BUILD_DIR/local.properties"

      - name: Build Android APK
        script: |
          gradle :app:assembleRelease

    artifacts:
      - app/build/outputs/**/*.apk
