workflows:
  android-apk:
    name: Jayemath Water Project V185 APK
    max_build_duration: 120

    scripts:
      - name: Set Android SDK location
        script: |
          echo "sdk.dir=$ANDROID_SDK_ROOT" > "$CM_BUILD_DIR/local.properties"

      - name: Build Android APK
        script: |
          gradle assembleRelease

    artifacts:
      - app/build/outputs/**/*.apk
