plugins {
    id 'com.android.application'
}

android {
    namespace 'com.jayemath.waterprint'
    compileSdk 35

    defaultConfig {
        applicationId 'com.jayemath.waterprint'
        minSdk 23
        targetSdk 35
        versionCode 185
        versionName "1.85"
    }

    signingConfigs {
        release {
            if (System.getenv("CM_KEYSTORE_PATH") != null) {
                storeFile file(System.getenv("CM_KEYSTORE_PATH"))
                storePassword System.getenv("CM_KEYSTORE_PASSWORD")
                keyAlias System.getenv("CM_KEY_ALIAS")
                keyPassword System.getenv("CM_KEY_PASSWORD")
            }
        }
    }

    buildTypes {
        release {
            minifyEnabled false
            signingConfig signingConfigs.release
        }
    }
}
